function [coeff] = generate_random_FDN_parameters(IRLength, numInput, numOutput)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    N = 2^randi(6);
   coeff = struct( ...
        'N', N, ...
        'length', IRLength, ...
        'inputGain', 2.*rand(N,numInput) - 1, ...
        'outputGain', 2.*rand(numOutput,N) -1, ...
        'feedbackMatrix', randomOrthogonal(N), ...
        'delays', randi([50,5000],[1,N]), ...
        'centerFrequencies', [ 63, 125, 250, 500, 1000, 2000, 4000, 8000], ...
        'targetT60', 6.*rand(10,1));
end

